### ISSUE TITLE
Please add a license file to the repository to make the license question crystal clear

### ISSUE THREAD

**Issue by dancesWithCycles** [wdr-data/reichweitenchecker#2]
Hi folks,
Thank you so much for providing and maintaining this repository.

[Here](https://data.wdr.de/ddj/reichweitenchecker/#faq) you mention you are in favor of the campaign [public money public code](https://publiccode.eu/en/). Me being a member of the fsfe makes it happy to read that! :-)

To make your statement crystal clear, do you mind adding a license file to this repository?

Here is a good [list](https://www.gnu.org/licenses/license-list.html) of suitable licenses.

I can recommend this license [file](https://git.wtf-eg.de/dancesWithCycles/delfi/src/branch/main/LICENSE).

Cheers!

**Comment by jh0ker** [comment]
Done 👍
